name: Deploy frontend to Edgeserver.IO
on:
  push:
    branches:
      - "main"
jobs:
  dostuff:
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - name: Build
        run: yarn build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "130396976851193856"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGETOKEN }}
          directory: dist